/// Flutter icons MonoIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MonoIcons
///      fonts:
///       - asset: fonts/MonoIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MonoIcons {
  MonoIcons._();

  static const _kFontFam = 'MonoIcons';
  static const String? _kFontPkg = null;

  static const IconData add = IconData(0xf101, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_up = IconData(0xf108, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xf11b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_add = IconData(0xf124, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_check = IconData(0xf130, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xf134, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xf140, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xf14c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xf15d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xf160, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xf16b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData options_horizontal = IconData(0xf179, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData options_vertical = IconData(0xf17a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xf18c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart = IconData(0xf18f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock = IconData(0xf1a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xf1ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
